export const SET_BOOKS = 'SET_BOOKS';
export const LOAD_BOOKS = 'LOAD_BOOKS';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_ITEMS_PER_PAGE = 'SET_ITEMS_PER_PAGE';
export const SET_SELECTED_BOOK='SET_SELECTED_BOOK'
export const LOAD_SELECTOR_BOOK='LOAD_SELECTOR_BOOK'
export const SEARCH_BOOKS='SEARCH_BOOKS'