export const  SIGN_UP_USER='SIGN_UP_USER'
export const ACTIVATE_SIGN_UP='ACTIVATE_SIGN_UP'
export const SIGN_IN_USER='SIGN_IN_USER'
export const GET_USER_INFO='GET_USER_INFO'
export const SET_USER='SET_USER'
